<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>

    <AssemblyName>PlexampRPC</AssemblyName>
    <Version>1.6.1</Version>
    <Copyright>Copyright © 2025 Dyvinia</Copyright>
    <Company>Dyvinia</Company>
    <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>

    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(MSBuildProjectName)\</PathMap>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="DiscordRichPresence" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Plex.Api" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**" />
  </ItemGroup>

</Project>
